"""
Skill Taxonomy - Standardized skill definitions with aliases.
Inspired by ESCO and O*NET skill frameworks.
"""

SKILL_TAXONOMY = [
    # --- Programming Languages ---
    {
        "name": "Python",
        "category": "Programming Languages",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["python programming", "python language", "python3", "py", "python 3"],
        "description": "General-purpose programming language widely used in AI/ML, data science, and web development.",
        "related": ["Machine Learning", "Data Analysis", "FastAPI", "Django"],
    },
    {
        "name": "JavaScript",
        "category": "Programming Languages",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["js", "javascript programming", "es6", "es2015+", "ecmascript"],
        "description": "Dynamic programming language for web development.",
        "related": ["React", "Node.js", "TypeScript"],
    },
    {
        "name": "TypeScript",
        "category": "Programming Languages",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["ts", "typescript programming", "typed javascript"],
        "description": "Typed superset of JavaScript.",
        "related": ["JavaScript", "React", "Node.js"],
    },
    {
        "name": "Java",
        "category": "Programming Languages",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["java programming", "core java", "java se", "java ee"],
        "description": "Object-oriented programming language widely used in enterprise applications.",
        "related": ["Spring Boot", "Microservices"],
    },
    {
        "name": "C++",
        "category": "Programming Languages",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["cpp", "c plus plus", "c/c++"],
        "description": "Systems programming language with high performance.",
        "related": ["Data Structures", "Algorithms"],
    },
    {
        "name": "SQL",
        "category": "Databases",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["structured query language", "sql queries", "database querying", "relational sql"],
        "description": "Standard language for relational database management.",
        "related": ["PostgreSQL", "MySQL", "Database Design"],
    },
    {
        "name": "R",
        "category": "Programming Languages",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["r programming", "r language", "r statistical"],
        "description": "Statistical computing and data analysis language.",
        "related": ["Statistics", "Data Analysis", "Data Visualization"],
    },

    # --- Web Frameworks ---
    {
        "name": "React",
        "category": "Web Development",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["reactjs", "react.js", "react js", "react framework"],
        "description": "JavaScript library for building user interfaces.",
        "related": ["JavaScript", "TypeScript", "Redux"],
    },
    {
        "name": "FastAPI",
        "category": "Web Development",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["fast api", "fastapi framework", "python fastapi"],
        "description": "Modern Python web framework for building REST APIs.",
        "related": ["Python", "REST APIs", "Pydantic"],
    },
    {
        "name": "Django",
        "category": "Web Development",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["django framework", "django rest framework", "drf"],
        "description": "Full-stack Python web framework.",
        "related": ["Python", "REST APIs"],
    },
    {
        "name": "Node.js",
        "category": "Web Development",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["nodejs", "node js", "node", "express.js", "expressjs"],
        "description": "Server-side JavaScript runtime.",
        "related": ["JavaScript", "TypeScript", "REST APIs"],
    },
    {
        "name": "Spring Boot",
        "category": "Web Development",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["spring", "spring framework", "spring mvc", "springboot"],
        "description": "Java framework for building production-ready applications.",
        "related": ["Java", "Microservices"],
    },

    # --- AI/ML ---
    {
        "name": "Machine Learning",
        "category": "Artificial Intelligence",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["ml", "machine-learning", "machine learning algorithms", "supervised learning", "unsupervised learning", "ml algorithms"],
        "description": "Building systems that learn from data to make predictions or decisions.",
        "related": ["Python", "Deep Learning", "scikit-learn", "Data Analysis"],
    },
    {
        "name": "Deep Learning",
        "category": "Artificial Intelligence",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["dl", "neural networks", "deep neural networks", "ann", "cnn", "rnn"],
        "description": "Subset of machine learning using multi-layer neural networks.",
        "related": ["Machine Learning", "TensorFlow", "PyTorch"],
    },
    {
        "name": "Natural Language Processing",
        "category": "Artificial Intelligence",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["nlp", "text processing", "text analytics", "computational linguistics", "language models"],
        "description": "Processing and analyzing natural language data.",
        "related": ["Machine Learning", "Python", "spaCy", "Transformers"],
    },
    {
        "name": "Computer Vision",
        "category": "Artificial Intelligence",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["cv", "image processing", "image recognition", "object detection"],
        "description": "Enabling computers to interpret visual information.",
        "related": ["Deep Learning", "OpenCV", "Python"],
    },
    {
        "name": "TensorFlow",
        "category": "AI/ML Frameworks",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["tensorflow", "tf", "keras", "tensorflow keras"],
        "description": "Open-source machine learning framework by Google.",
        "related": ["Deep Learning", "Python"],
    },
    {
        "name": "PyTorch",
        "category": "AI/ML Frameworks",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["pytorch", "torch"],
        "description": "Open-source machine learning framework by Meta.",
        "related": ["Deep Learning", "Python"],
    },
    {
        "name": "scikit-learn",
        "category": "AI/ML Frameworks",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["sklearn", "scikit learn", "scikit-learn library"],
        "description": "Machine learning library for Python.",
        "related": ["Machine Learning", "Python"],
    },

    # --- Data Science ---
    {
        "name": "Data Analysis",
        "category": "Data Science",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["data analytics", "exploratory data analysis", "eda", "data exploration"],
        "description": "Examining datasets to draw conclusions.",
        "related": ["Python", "SQL", "Statistics", "Pandas"],
    },
    {
        "name": "Statistics",
        "category": "Data Science",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["statistical analysis", "probability", "hypothesis testing", "statistical modeling"],
        "description": "Mathematical methods for data collection, analysis, and interpretation.",
        "related": ["Data Analysis", "Machine Learning", "R"],
    },
    {
        "name": "Pandas",
        "category": "Data Science",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["pandas library", "pandas dataframe", "python pandas"],
        "description": "Python library for data manipulation and analysis.",
        "related": ["Python", "Data Analysis", "NumPy"],
    },
    {
        "name": "NumPy",
        "category": "Data Science",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["numpy", "numerical python", "np"],
        "description": "Python library for numerical computing.",
        "related": ["Python", "Data Analysis", "Machine Learning"],
    },
    {
        "name": "Data Visualization",
        "category": "Data Science",
        "skill_type": "technical",
        "difficulty": "beginner",
        "aliases": ["data viz", "visualization", "matplotlib", "seaborn", "plotly", "tableau"],
        "description": "Creating visual representations of data.",
        "related": ["Data Analysis", "Python"],
    },

    # --- Databases ---
    {
        "name": "PostgreSQL",
        "category": "Databases",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["postgres", "postgresql database", "psql"],
        "description": "Advanced open-source relational database.",
        "related": ["SQL", "Database Design"],
    },
    {
        "name": "MySQL",
        "category": "Databases",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["my sql", "mysql database"],
        "description": "Popular open-source relational database.",
        "related": ["SQL", "Database Design"],
    },
    {
        "name": "MongoDB",
        "category": "Databases",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["mongo", "mongodb database", "nosql mongodb"],
        "description": "NoSQL document database.",
        "related": ["Database Design", "NoSQL"],
    },
    {
        "name": "Database Design",
        "category": "Databases",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["database architecture", "schema design", "er diagram", "normalization", "relational database design"],
        "description": "Designing efficient database schemas and relationships.",
        "related": ["SQL", "PostgreSQL", "MySQL"],
    },

    # --- Cloud & DevOps ---
    {
        "name": "AWS",
        "category": "Cloud Computing",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["amazon web services", "amazon aws", "aws cloud", "ec2", "s3", "lambda aws"],
        "description": "Amazon Web Services cloud platform.",
        "related": ["Cloud Computing", "Docker", "DevOps"],
    },
    {
        "name": "Google Cloud",
        "category": "Cloud Computing",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["gcp", "google cloud platform", "google cloud services"],
        "description": "Google Cloud Platform.",
        "related": ["Cloud Computing", "Docker"],
    },
    {
        "name": "Azure",
        "category": "Cloud Computing",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["microsoft azure", "azure cloud", "azure services"],
        "description": "Microsoft Azure cloud platform.",
        "related": ["Cloud Computing", "Docker"],
    },
    {
        "name": "Cloud Computing",
        "category": "Cloud Computing",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["cloud", "cloud services", "cloud infrastructure", "cloud deployment"],
        "description": "On-demand computing services over the internet.",
        "related": ["AWS", "Google Cloud", "Azure", "DevOps"],
    },
    {
        "name": "Docker",
        "category": "DevOps",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["containerization", "docker container", "docker compose", "containers"],
        "description": "Platform for building and running containerized applications.",
        "related": ["Kubernetes", "DevOps", "Cloud Computing"],
    },
    {
        "name": "Kubernetes",
        "category": "DevOps",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["k8s", "kubernetes orchestration", "container orchestration"],
        "description": "Container orchestration platform.",
        "related": ["Docker", "DevOps", "Cloud Computing"],
    },
    {
        "name": "DevOps",
        "category": "DevOps",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["dev ops", "ci/cd", "continuous integration", "continuous deployment", "devsecops"],
        "description": "Practices combining software development and IT operations.",
        "related": ["Docker", "Kubernetes", "Git"],
    },
    {
        "name": "Git",
        "category": "DevOps",
        "skill_type": "technical",
        "difficulty": "beginner",
        "aliases": ["git version control", "github", "gitlab", "version control", "source control"],
        "description": "Distributed version control system.",
        "related": ["DevOps", "GitHub"],
    },

    # --- Security ---
    {
        "name": "Cybersecurity",
        "category": "Security",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["information security", "infosec", "cyber security", "network security", "security engineering"],
        "description": "Protecting systems and networks from digital attacks.",
        "related": ["Networking", "Cryptography"],
    },
    {
        "name": "REST APIs",
        "category": "Web Development",
        "skill_type": "technical",
        "difficulty": "intermediate",
        "aliases": ["restful api", "rest api development", "api development", "http api", "web api", "api design"],
        "description": "Designing and building RESTful web services.",
        "related": ["FastAPI", "Django", "Node.js", "Spring Boot"],
    },
    {
        "name": "Data Engineering",
        "category": "Data Science",
        "skill_type": "technical",
        "difficulty": "advanced",
        "aliases": ["data pipelines", "etl", "data warehouse", "data lake", "apache spark"],
        "description": "Building and maintaining data pipelines and infrastructure.",
        "related": ["SQL", "Python", "Cloud Computing"],
    },

    # --- Soft Skills ---
    {
        "name": "Problem Solving",
        "category": "Soft Skills",
        "skill_type": "soft",
        "difficulty": "intermediate",
        "aliases": ["critical thinking", "analytical thinking", "troubleshooting"],
        "description": "Ability to identify and resolve complex problems.",
        "related": ["Communication", "Teamwork"],
    },
    {
        "name": "Communication",
        "category": "Soft Skills",
        "skill_type": "soft",
        "difficulty": "beginner",
        "aliases": ["verbal communication", "written communication", "presentation skills"],
        "description": "Effectively conveying information.",
        "related": ["Teamwork", "Leadership"],
    },
    {
        "name": "Teamwork",
        "category": "Soft Skills",
        "skill_type": "soft",
        "difficulty": "beginner",
        "aliases": ["collaboration", "team player", "cross-functional collaboration"],
        "description": "Working effectively in a team.",
        "related": ["Communication", "Leadership"],
    },
]

PROFICIENCY_LEVELS = {
    0: {"name": "No Evidence", "min_score": 0, "max_score": 0},
    1: {"name": "Beginner", "min_score": 1, "max_score": 20},
    2: {"name": "Basic", "min_score": 21, "max_score": 40},
    3: {"name": "Intermediate", "min_score": 41, "max_score": 60},
    4: {"name": "Advanced", "min_score": 61, "max_score": 80},
    5: {"name": "Expert", "min_score": 81, "max_score": 100},
}

EVIDENCE_WEIGHTS = {
    "assessment": 0.30,
    "project": 0.25,
    "certificate": 0.20,
    "internship": 0.20,
    "faculty_verified": 0.15,
    "industry_feedback": 0.15,
    "resume": 0.10,
    "self_declared": 0.05,
}

READINESS_THRESHOLDS = {
    "needs_improvement": (0, 39),
    "developing": (40, 59),
    "moderately_ready": (60, 74),
    "job_ready": (75, 89),
    "highly_ready": (90, 100),
}

SEMANTIC_MATCH_THRESHOLD = 0.65
